### ISSUE TITLE
Dependencies Question

### ISSUE THREAD

**Issue by AdrianAntico** [trinker/textshape#18]
Why does your Description File Imports not match your Dependency section on the README?

From your Description file, here are the imports (Imports: data.table, slam, stats, stringi, utils) but the Dependency section lists

```
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, magrittr, ggstance, viridis, gridExtra, textreadr, quanteda)
pacman::p_load_current_gh('trinker/gofastr', 'trinker/textshape')
```

**Comment by trinker** [comment]
This is likely human error on my part.  Can you investigate further, fix,
and send a pull request?

**Comment by trinker** [comment]
Coming back to this.  The dependencies was the dependencies of the script not the package.
